#!/usr/bin/env python

import sys
import os.path

for arg in sys.argv:
    print arg
base_command = os.path.basename(sys.argv[0])

print base_command
print len(sys.argv)
#command_paths = [base]

usage = "usage: lotto_analysis"
